using System.Collections.Generic;
using UnityEngine;

namespace CoopView
{
    static class KeyCodeMaps
    {
        public enum Keys
        {
            Modifiers = -65536,
            None = 0,
            Back = 8,
            Tab = 9,
            Clear = 12,
            Enter = 13,
            Shift = 16,
            Control = 17,
            Alt = 18,
            Pause = 19,
            Capital = 20,
            CapsLock = 20,
            Escape = 27,
            Space = 32,
            PageUp = 33,
            PageDown = 34,
            End = 35,
            Home = 36,
            Left = 37,
            Up = 38,
            Right = 39,
            Down = 40,
            Print = 42,
            PrintScreen = 44,
            Insert = 45,
            Delete = 46,
            D0 = 48,
            D1 = 49,
            D2 = 50,
            D3 = 51,
            D4 = 52,
            D5 = 53,
            D6 = 54,
            D7 = 55,
            D8 = 56,
            D9 = 57,
            A = 65,
            B = 66,
            C = 67,
            D = 68,
            E = 69,
            F = 70,
            G = 71,
            H = 72,
            I = 73,
            J = 74,
            K = 75,
            L = 76,
            M = 77,
            N = 78,
            O = 79,
            P = 80,
            Q = 81,
            R = 82,
            S = 83,
            T = 84,
            U = 85,
            V = 86,
            W = 87,
            X = 88,
            Y = 89,
            Z = 90,
            NumPad0 = 96,
            NumPad1 = 97,
            NumPad2 = 98,
            NumPad3 = 99,
            NumPad4 = 100,
            NumPad5 = 101,
            NumPad6 = 102,
            NumPad7 = 103,
            NumPad8 = 104,
            NumPad9 = 105,
            Multiply = 106,
            Add = 107,
            Separator = 108,
            Subtract = 109,
            Decimal = 110,
            Divide = 111,
            F1 = 112,
            F2 = 113,
            F3 = 114,
            F4 = 115,
            F5 = 116,
            F6 = 117,
            F7 = 118,
            F8 = 119,
            F9 = 120,
            F10 = 121,
            F11 = 122,
            F12 = 123,
            F13 = 124,
            F14 = 125,
            F15 = 126,
            F16 = 127,
            F17 = 128,
            F18 = 129,
            F19 = 130,
            F20 = 131,
            F21 = 132,
            F22 = 133,
            F23 = 134,
            F24 = 135,
            NumLock = 144,
            Scroll = 145,
            OemSemicolon = 186,
            Oem1 = 186,
            Oemplus = 187,
            Oemcomma = 188,
            OemMinus = 189,
            OemPeriod = 190,
            OemQuestion = 191,
            Oem2 = 191,
            Oemtilde = 192,
            Oem3 = 192,
            OemOpenBrackets = 219,
            Oem4 = 219,
            OemPipe = 220,
            Oem5 = 220,
            OemCloseBrackets = 221,
            Oem6 = 221,
            OemQuotes = 222,
            Oem7 = 222,
            Oem8 = 223,
            OemBackslash = 226,
            KeyCode = 65535,
        }

        public static Dictionary<KeyCode, Keys> KeyCodeToKeysMap = new Dictionary<KeyCode, Keys>
        {
            { KeyCode.A, Keys.A },
            { KeyCode.B, Keys.B },
            { KeyCode.C, Keys.C },
            { KeyCode.D, Keys.D },
            { KeyCode.E, Keys.E },
            { KeyCode.F, Keys.F },
            { KeyCode.G, Keys.G },
            { KeyCode.H, Keys.H },
            { KeyCode.I, Keys.I },
            { KeyCode.J, Keys.J },
            { KeyCode.K, Keys.K },
            { KeyCode.L, Keys.L },
            { KeyCode.M, Keys.M },
            { KeyCode.N, Keys.N },
            { KeyCode.O, Keys.O },
            { KeyCode.P, Keys.P },
            { KeyCode.Q, Keys.Q },
            { KeyCode.R, Keys.R },
            { KeyCode.S, Keys.S },
            { KeyCode.T, Keys.T },
            { KeyCode.U, Keys.U },
            { KeyCode.V, Keys.V },
            { KeyCode.W, Keys.W },
            { KeyCode.X, Keys.X },
            { KeyCode.Y, Keys.Y },
            { KeyCode.Z, Keys.Z },

            { KeyCode.Alpha0, Keys.D0 },
            { KeyCode.Alpha1, Keys.D1 },
            { KeyCode.Alpha2, Keys.D2 },
            { KeyCode.Alpha3, Keys.D3 },
            { KeyCode.Alpha4, Keys.D4 },
            { KeyCode.Alpha5, Keys.D5 },
            { KeyCode.Alpha6, Keys.D6 },
            { KeyCode.Alpha7, Keys.D7 },
            { KeyCode.Alpha8, Keys.D8 },
            { KeyCode.Alpha9, Keys.D9 },

            { KeyCode.F1, Keys.F1 },
            { KeyCode.F2, Keys.F2 },
            { KeyCode.F3, Keys.F3 },
            { KeyCode.F4, Keys.F4 },
            { KeyCode.F5, Keys.F5 },
            { KeyCode.F6, Keys.F6 },
            { KeyCode.F7, Keys.F7 },
            { KeyCode.F8, Keys.F8 },
            { KeyCode.F9, Keys.F9 },
            { KeyCode.F10, Keys.F10 },
            { KeyCode.F11, Keys.F11 },
            { KeyCode.F12, Keys.F12 },

            { KeyCode.LeftControl, Keys.Control },
            { KeyCode.RightControl, Keys.Control },
            { KeyCode.LeftShift, Keys.Shift },
            { KeyCode.RightShift, Keys.Shift },
            { KeyCode.LeftAlt, Keys.Alt },
            { KeyCode.RightAlt, Keys.Alt },

            { KeyCode.Space, Keys.Space },
            { KeyCode.Return, Keys.Enter },
            { KeyCode.Backspace, Keys.Back },
            { KeyCode.Escape, Keys.Escape },
            { KeyCode.Tab, Keys.Tab },
            { KeyCode.CapsLock, Keys.Capital },
            { KeyCode.Delete, Keys.Delete },
            { KeyCode.Insert, Keys.Insert },
            { KeyCode.Home, Keys.Home },
            { KeyCode.End, Keys.End },
            { KeyCode.PageUp, Keys.PageUp },
            { KeyCode.PageDown, Keys.PageDown },
            { KeyCode.UpArrow, Keys.Up },
            { KeyCode.DownArrow, Keys.Down },
            { KeyCode.LeftArrow, Keys.Left },
            { KeyCode.RightArrow, Keys.Right },

            { KeyCode.Semicolon, Keys.OemSemicolon },
            { KeyCode.Slash, Keys.Oem2 },
            { KeyCode.Backslash, Keys.Oem5 },
            { KeyCode.LeftBracket, Keys.Oem4 },
            { KeyCode.RightBracket, Keys.Oem6 },
            { KeyCode.Quote, Keys.Oem7 },
            { KeyCode.BackQuote, Keys.Oem3 },
            { KeyCode.Minus, Keys.OemMinus },
            { KeyCode.Equals, Keys.Oemplus },
            { KeyCode.Comma, Keys.Oemcomma },
            { KeyCode.Period, Keys.OemPeriod },

            { KeyCode.Keypad0, Keys.NumPad0 },
            { KeyCode.Keypad1, Keys.NumPad1 },
            { KeyCode.Keypad2, Keys.NumPad2 },
            { KeyCode.Keypad3, Keys.NumPad3 },
            { KeyCode.Keypad4, Keys.NumPad4 },
            { KeyCode.Keypad5, Keys.NumPad5 },
            { KeyCode.Keypad6, Keys.NumPad6 },
            { KeyCode.Keypad7, Keys.NumPad7 },
            { KeyCode.Keypad8, Keys.NumPad8 },
            { KeyCode.Keypad9, Keys.NumPad9 },
            { KeyCode.KeypadDivide, Keys.Divide },
            { KeyCode.KeypadMultiply, Keys.Multiply },
            { KeyCode.KeypadMinus, Keys.Subtract },
            { KeyCode.KeypadPlus, Keys.Add },
            { KeyCode.KeypadEnter, Keys.Enter },
            { KeyCode.KeypadPeriod, Keys.Decimal },

            { KeyCode.Print, Keys.PrintScreen },
            { KeyCode.ScrollLock, Keys.Scroll },
            { KeyCode.Pause, Keys.Pause },
        };

        public static Dictionary<KeyCode, string> KeyCodeToStringMap = new Dictionary<KeyCode, string>
        {
            { KeyCode.A, "A" },
            { KeyCode.B, "B" },
            { KeyCode.C, "C" },
            { KeyCode.D, "D" },
            { KeyCode.E, "E" },
            { KeyCode.F, "F" },
            { KeyCode.G, "G" },
            { KeyCode.H, "H" },
            { KeyCode.I, "I" },
            { KeyCode.J, "J" },
            { KeyCode.K, "K" },
            { KeyCode.L, "L" },
            { KeyCode.M, "M" },
            { KeyCode.N, "N" },
            { KeyCode.O, "O" },
            { KeyCode.P, "P" },
            { KeyCode.Q, "Q" },
            { KeyCode.R, "R" },
            { KeyCode.S, "S" },
            { KeyCode.T, "T" },
            { KeyCode.U, "U" },
            { KeyCode.V, "V" },
            { KeyCode.W, "W" },
            { KeyCode.X, "X" },
            { KeyCode.Y, "Y" },
            { KeyCode.Z, "Z" },

            { KeyCode.Alpha0, "0" },
            { KeyCode.Alpha1, "1" },
            { KeyCode.Alpha2, "2" },
            { KeyCode.Alpha3, "3" },
            { KeyCode.Alpha4, "4" },
            { KeyCode.Alpha5, "5" },
            { KeyCode.Alpha6, "6" },
            { KeyCode.Alpha7, "7" },
            { KeyCode.Alpha8, "8" },
            { KeyCode.Alpha9, "9" },

            { KeyCode.F1, "F1" },
            { KeyCode.F2, "F2" },
            { KeyCode.F3, "F3" },
            { KeyCode.F4, "F4" },
            { KeyCode.F5, "F5" },
            { KeyCode.F6, "F6" },
            { KeyCode.F7, "F7" },
            { KeyCode.F8, "F8" },
            { KeyCode.F9, "F9" },
            { KeyCode.F10, "F10" },
            { KeyCode.F11, "F11" },
            { KeyCode.F12, "F12" },

            { KeyCode.LeftControl, "Ctrl" },
            { KeyCode.RightControl, "Ctrl" },
            { KeyCode.LeftShift, "Shift" },
            { KeyCode.RightShift, "Shift" },
            { KeyCode.LeftAlt, "Alt" },
            { KeyCode.RightAlt, "Alt" },

            { KeyCode.Space, "Space" },
            { KeyCode.Return, "Enter" },
            { KeyCode.Backspace, "Backspace" },
            { KeyCode.Escape, "Escape" },
            { KeyCode.Tab, "Tab" },
            { KeyCode.CapsLock, "CapsLock" },
            { KeyCode.Delete, "Delete" },
            { KeyCode.Insert, "Insert" },
            { KeyCode.Home, "Home" },
            { KeyCode.End, "End" },
            { KeyCode.PageUp, "PageUp" },
            { KeyCode.PageDown, "PageDown" },
            { KeyCode.UpArrow, "Up" },
            { KeyCode.DownArrow, "Down" },
            { KeyCode.LeftArrow, "Left" },
            { KeyCode.RightArrow, "Right" },

            { KeyCode.Semicolon, ";" },
            { KeyCode.Slash, "/" },
            { KeyCode.Backslash, "\\" },
            { KeyCode.LeftBracket, "[" },
            { KeyCode.RightBracket, "]" },
            { KeyCode.Quote, "'" },
            { KeyCode.BackQuote, "`" },
            { KeyCode.Minus, "-" },
            { KeyCode.Equals, "=" },
            { KeyCode.Comma, "," },
            { KeyCode.Period, "." },

            { KeyCode.Keypad0, "Num0" },
            { KeyCode.Keypad1, "Num1" },
            { KeyCode.Keypad2, "Num2" },
            { KeyCode.Keypad3, "Num3" },
            { KeyCode.Keypad4, "Num4" },
            { KeyCode.Keypad5, "Num5" },
            { KeyCode.Keypad6, "Num6" },
            { KeyCode.Keypad7, "Num7" },
            { KeyCode.Keypad8, "Num8" },
            { KeyCode.Keypad9, "Num9" },
            { KeyCode.KeypadDivide, "Num/" },
            { KeyCode.KeypadMultiply, "Num*" },
            { KeyCode.KeypadMinus, "Num-" },
            { KeyCode.KeypadPlus, "Num+" },
            { KeyCode.KeypadEnter, "NumEnter" },
            { KeyCode.KeypadPeriod, "Num." },

            { KeyCode.Print, "PrintScreen" },
            { KeyCode.ScrollLock, "Scroll" },
            { KeyCode.Pause, "Pause" },
        };

        public static Dictionary<Keys, KeyCode> KeysToKeyCodeMap = new Dictionary<Keys, KeyCode>
        {
            { Keys.A, KeyCode.A },
            { Keys.B, KeyCode.B },
            { Keys.C, KeyCode.C },
            { Keys.D, KeyCode.D },
            { Keys.E, KeyCode.E },
            { Keys.F, KeyCode.F },
            { Keys.G, KeyCode.G },
            { Keys.H, KeyCode.H },
            { Keys.I, KeyCode.I },
            { Keys.J, KeyCode.J },
            { Keys.K, KeyCode.K },
            { Keys.L, KeyCode.L },
            { Keys.M, KeyCode.M },
            { Keys.N, KeyCode.N },
            { Keys.O, KeyCode.O },
            { Keys.P, KeyCode.P },
            { Keys.Q, KeyCode.Q },
            { Keys.R, KeyCode.R },
            { Keys.S, KeyCode.S },
            { Keys.T, KeyCode.T },
            { Keys.U, KeyCode.U },
            { Keys.V, KeyCode.V },
            { Keys.W, KeyCode.W },
            { Keys.X, KeyCode.X },
            { Keys.Y, KeyCode.Y },
            { Keys.Z, KeyCode.Z },

            { Keys.D0, KeyCode.Alpha0 },
            { Keys.D1, KeyCode.Alpha1 },
            { Keys.D2, KeyCode.Alpha2 },
            { Keys.D3, KeyCode.Alpha3 },
            { Keys.D4, KeyCode.Alpha4 },
            { Keys.D5, KeyCode.Alpha5 },
            { Keys.D6, KeyCode.Alpha6 },
            { Keys.D7, KeyCode.Alpha7 },
            { Keys.D8, KeyCode.Alpha8 },
            { Keys.D9, KeyCode.Alpha9 },

            { Keys.F1, KeyCode.F1 },
            { Keys.F2, KeyCode.F2 },
            { Keys.F3, KeyCode.F3 },
            { Keys.F4, KeyCode.F4 },
            { Keys.F5, KeyCode.F5 },
            { Keys.F6, KeyCode.F6 },
            { Keys.F7, KeyCode.F7 },
            { Keys.F8, KeyCode.F8 },
            { Keys.F9, KeyCode.F9 },
            { Keys.F10, KeyCode.F10 },
            { Keys.F11, KeyCode.F11 },
            { Keys.F12, KeyCode.F12 },

            { Keys.Control, KeyCode.LeftControl },
            { Keys.Shift, KeyCode.LeftShift },
            { Keys.Alt, KeyCode.LeftAlt },

            { Keys.Space, KeyCode.Space },
            { Keys.Enter, KeyCode.Return },
            { Keys.Back, KeyCode.Backspace },
            { Keys.Escape, KeyCode.Escape },
            { Keys.Tab, KeyCode.Tab },
            { Keys.Capital, KeyCode.CapsLock },
            { Keys.Delete, KeyCode.Delete },
            { Keys.Insert, KeyCode.Insert },
            { Keys.Home, KeyCode.Home },
            { Keys.End, KeyCode.End },
            { Keys.PageUp, KeyCode.PageUp },
            { Keys.PageDown, KeyCode.PageDown },
            { Keys.Up, KeyCode.UpArrow },
            { Keys.Down, KeyCode.DownArrow },
            { Keys.Left, KeyCode.LeftArrow },
            { Keys.Right, KeyCode.RightArrow },

            { Keys.OemSemicolon, KeyCode.Semicolon },
            { Keys.Oem2, KeyCode.Slash },
            { Keys.Oem5, KeyCode.Backslash },
            { Keys.Oem4, KeyCode.LeftBracket },
            { Keys.Oem6, KeyCode.RightBracket },
            { Keys.Oem7, KeyCode.Quote },
            { Keys.Oem3, KeyCode.BackQuote },
            { Keys.OemMinus, KeyCode.Minus },
            { Keys.Oemplus, KeyCode.Equals },
            { Keys.Oemcomma, KeyCode.Comma },
            { Keys.OemPeriod, KeyCode.Period },

            { Keys.NumPad0, KeyCode.Keypad0 },
            { Keys.NumPad1, KeyCode.Keypad1 },
            { Keys.NumPad2, KeyCode.Keypad2 },
            { Keys.NumPad3, KeyCode.Keypad3 },
            { Keys.NumPad4, KeyCode.Keypad4 },
            { Keys.NumPad5, KeyCode.Keypad5 },
            { Keys.NumPad6, KeyCode.Keypad6 },
            { Keys.NumPad7, KeyCode.Keypad7 },
            { Keys.NumPad8, KeyCode.Keypad8 },
            { Keys.NumPad9, KeyCode.Keypad9 },
            { Keys.Divide, KeyCode.KeypadDivide },
            { Keys.Multiply, KeyCode.KeypadMultiply },
            { Keys.Subtract, KeyCode.KeypadMinus },
            { Keys.Add, KeyCode.KeypadPlus },
            { Keys.Decimal, KeyCode.KeypadPeriod },

            { Keys.PrintScreen, KeyCode.Print },
            { Keys.Scroll, KeyCode.ScrollLock },
            { Keys.Pause, KeyCode.Pause },
        };
    }
}
